export interface talent {
  email: String,
  firstName: String,
  lastName: String,
  isoCode: String,
  residence: String,
  zipCode: String,
  city: String,
  occupationId: String,
  positionName: String,
  occupationStatusId: String,
  employerName: String,
  studyProgram: String,
  university: String,
  expectedGraduationYear: String,
}